// Mock lightweight front-end logic to demonstrate features.


const contractors = [
{name:'Westwood Builders',type:'General Builder',rating:4.7,rate:300},
{name:'Skyline Roofing',type:'Roofing',rating:4.5,rate:280},
{name:'Bright Spark Electrics',type:'Electrician',rating:4.8,rate:220},
{name:'PureFlow Plumbing',type:'Plumber',rating:4.6,rate:200}
];


function currency(x){ return '£'+x.toLocaleString(undefined,{maximumFractionDigits:0}); }


// Estimate
const form = document.getElementById('estimateForm');
form.addEventListener('submit', (e)=>{
e.preventDefault();
const name = document.getElementById('projName').value || 'Untitled project';
const area = Number(document.getElementById('area').value) || 0;
const costPer = Number(document.getElementById('costPerM2').value) || 0;
const weeks = Number(document.getElementById('weeks').value) || 0;


// simple algorithm + contingency
const base = area * costPer;
const contingency = Math.round(base * 0.08); // 8%
const labour = weeks * 5000; // mock labour bucket
const total = Math.round(base + contingency + labour);


const timeline = generateTimeline(weeks);


document.getElementById('estimateResult').innerHTML = `
<strong>${name}</strong>
<div>Base cost: ${currency(base)}</div>
<div>Contingency (8%): ${currency(contingency)}</div>
<div>Labour estimate: ${currency(labour)}</div>
<div style="margin-top:8px">Total estimate: <strong>${currency(total)}</strong></div>
<details style="margin-top:8px"><summary>Project timeline</summary><pre>${timeline}</pre></details>
`;
});


function generateTimeline(weeks){
if(weeks<=0) return 'No timeline';
const phases = ['Survey & design','Procurement','Construction','Finishing & snagging'];
const per = Math.max(1, Math.round(weeks / phases.length));
let out = '';
let start = 1;
for(let i=0;i<phases.length;i++){
const end = Math.min(weeks, start + per -1);
out += ${phases[i]}: week ${start} - ${end}\n;
start = end + 1;
if(start>weeks) break;
}
return out;
}


// Documents (CDM/RAMS) generation — generate text file and provide download link


function makeDownloadFile(filename, content){
const blob = new Blob([content],{type:'text/plain'});
const url = URL.createObjectURL(blob);
const a = document.createElement('a');
a.href = url; a.download = filename; a.textContent = Download ${filename};
return a;
}


const genDocsBtn = document.getElementById('genDocs');
genDocsBtn.addEventListener('click', ()=>{
const hazards = document.getElementById('hazards').value || 'None listed';
const cdm = CDM Compliance Report\nProject hazards: ${hazards}\nGenerated by BuildNexus prototype;
const rams = RAMS - Risk Assessment and Method Statement\nHazards: ${hazards}\nControls: Use competent contractors, proper PPE, signage.;
const container = document.getElementById('docLinks');
container.innerHTML='';
container.appendChild(makeDownloadFile('CDM-report.txt',cdm));